### ISSUE TITLE
可以集成一下这两个插件，自定义打印

### ISSUE THREAD

**Issue by richard1015** [xtfge/vue-cesium-draw#2]
https://github.com/richard1015/cesium-print
https://github.com/richard1015/cesium-navigation-es6

**Comment by xtfge** [comment]
谢谢你的建议,我会抽时间研究的.

**Comment by xtfge** [comment]
这两个插件非常有用，后续这个项目会发展成一个插件，本身并不包括球，所以我觉得这个集成工作应该由用户完成。谢谢你的建议。
