### ISSUE TITLE
多边形绘制报错

### ISSUE THREAD

**Issue by finanshow** [xtfge/vue-cesium-draw#4]
![capture](https://user-images.githubusercontent.com/3020818/64500001-0b96ea80-d2ee-11e9-9f9b-a112e36a6808.png)

**Comment by xtfge** [comment]
请使用1.5x版本的Cesium,使用1.6.x的Cesium就会出现这种错误,应该是版本更新带来的bug

**Comment by finanshow** [comment]
> 请使用1.5x版本的Cesium
嗯，刚下载github你最新的
Cesium版本号:1.56.1

**Comment by finanshow** [comment]
> 请使用1.5x版本的Cesium

When npm install 1.5x version of Cesium, it occur this error. The access_token seems like doesn't work well.
![c1](https://user-images.githubusercontent.com/3020818/64542523-4cc2e500-d356-11e9-9494-f829eeb00ee1.png)
![Uploading c2.png…]()

**Comment by finanshow** [comment]
> 请使用1.5x版本的Cesium
> 
> When npm install 1.5x version of Cesium, it occur this error. The access_token seems like doesn't work well.

Add this before create a cesium viewer.
      Cesium.Ion.defaultAccessToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1NWI5MGUzNi1mYWI3LTQzY2QtOGI0Ni0xZWYyNTAxNGM4N2MiLCJpZCI6MTI1OTgsInNjb3BlcyI6WyJhc3IiLCJnYyJdLCJpYXQiOjE1NjE0NDkyNTV9.hBH0PGSnKErc_yNhIePASUkr3QPDoo0KDX9uLpNBUns';

**Comment by skywalkershen** [comment]
请问知道是具体什么错误导致的吗？如果要在1.6使用，需要做哪些方面的更改呢？多谢

**Comment by xtfge** [comment]
> 请问知道是具体什么错误导致的吗？如果要在1.6使用，需要做哪些方面的更改呢？多谢

还没有研究为什么会出现这种问题，我会尽快解决的

**Comment by xtfge** [comment]
已解决。
