### ISSUE TITLE
打包后报错，请问下怎么解决啊

### ISSUE THREAD

**Issue by 393313107** [xtfge/vue-cesium-draw#5]

**Comment by xtfge** [comment]
请详细描述你的错误信息。

> _No description provided._

**Comment by 393313107** [comment]
> 请详细描述你的错误信息。
> 
> > _No description provided._

我build后上传服务器了，http://www.funnywork.com/demos/#/   你F12看一下，好像是本地静态文件都404，不太懂怎么改配置，麻烦您看下，刚好在学习这个，挺感兴趣的

**Comment by xtfge** [comment]
应该是资源没有上传或着没有打包，你可以对照报错的地址和服务器上的文件。
此外，我在今天晚上更新的版本中添加了打包后的代码，你可以直接使用，或更新最新版后打包。
