### ISSUE TITLE
我想把这个拉成一个vue组件用到我的项目中，按方法操作报错

### ISSUE THREAD

**Issue by 393313107** [xtfge/vue-cesium-draw#7]
These dependencies were not found:

* cesium/Cesium in ./src/js/utils.js, ./src/js/Convert.js and 1 other
* file-saver in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/se
lector.js?type=script&index=0!./src/components/marker.vue, ./src/js/drawHandler.
js
* shapefile in ./src/js/utils.js
* xlsx in ./src/js/utils.js

To install them, you can run: npm install --save cesium/Cesium file-saver shapef
ile xlsx

These relative modules were not found:

* ../../static/images/markers/markPanel/download.png in ./node_modules/css-loade
r?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"i
d":"data-v-ae3f28f4","scoped":true,"hasInlineConfig":false}!./node_modules/vue-l
oader/lib/selector.js?type=styles&index=0!./src/components/drawViewer.vue
* ../../static/images/markers/markPanel/marker.png in ./node_modules/css-loader?
{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id"
:"data-v-ae3f28f4","scoped":true,"hasInlineConfig":false}!./node_modules/vue-loa
der/lib/selector.js?type=styles&index=0!./src/components/drawViewer.vue
* ../../static/images/markers/markPanel/polygon.png in ./node_modules/css-loader
?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id
":"data-v-ae3f28f4","scoped":true,"hasInlineConfig":false}!./node_modules/vue-lo
ader/lib/selector.js?type=styles&index=0!./src/components/drawViewer.vue
* ../../static/images/markers/markPanel/polyline.png in ./node_modules/css-loade
r?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"i
d":"data-v-ae3f28f4","scoped":true,"hasInlineConfig":false}!./node_modules/vue-l
oader/lib/selector.js?type=styles&index=0!./src/components/drawViewer.vue
* ../../static/images/markers/markPanel/remove.png in ./node_modules/css-loader?
{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id"
:"data-v-ae3f28f4","scoped":true,"hasInlineConfig":false}!./node_modules/vue-loa
der/lib/selector.js?type=styles&index=0!./src/components/drawViewer.vue
* ../../static/images/markers/markPanel/upload.png in ./node_modules/css-loader?
{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id"
:"data-v-ae3f28f4","scoped":true,"hasInlineConfig":false}!./node_modules/vue-loa
der/lib/selector.js?type=styles&index=0!./src/components/drawViewer.vue

**Comment by xtfge** [comment]
报错是因为文件路径的原因，建议仔细检查文件路径和引用路径是否一致，此外你的代码不是最新版，建议更新

**Comment by 393313107** [comment]
> 报错是因为文件路径的原因，建议仔细检查文件路径和引用路径是否一致，此外你的代码不是最新版，建议更新

你的方法收只复制那几个组件和js文件夹，是否还需要npm什么包呢之类的详细方法

**Comment by xtfge** [comment]
> > 报错是因为文件路径的原因，建议仔细检查文件路径和引用路径是否一致，此外你的代码不是最新版，建议更新
> 
> 你的方法收只复制那几个组件和js文件夹，是否还需要npm什么包呢之类的详细方法

首先，你要把所有的静态文件和代码全部复制过去，
其次，把package.json中的包添加到自己的package.json中。
最后，你需要npm install

**Comment by 393313107** [comment]
> > > 报错是因为文件路径的原因，建议仔细检查文件路径和引用路径是否一致，此外你的代码不是最新版，建议更新
> > 
> > 
> > 你的方法收只复制那几个组件和js文件夹，是否还需要npm什么包呢之类的详细方法
> 
> 首先，你要把所有的静态文件和代码全部复制过去，
> 其次，把package.json中的包添加到自己的package.json中。
> 最后，你需要npm install

我按照您说的方法去试过了，该装的包也已经装了，webpack的配置也设置了，还是报缺东西的报错，或者您方便留个V吗，帮我看一眼。cesium包已经npm过了，缓存清了，重新跑webpack了依旧如此
 ERROR  Failed to compile with 1 errors


This dependency was not found:

* cesium/Cesium in ./src/main.js

To install it, you can run: npm install --save cesium/Cesium

**Comment by xtfge** [comment]
在mian.js中删除 
`import Cesium from 'cesium/Cesium`
如果搞不定可以加我QQ:874406328
