### ISSUE TITLE
性能问题，画多个图形后帧率明显下降

### ISSUE THREAD

**Issue by skywalkershen** [xtfge/vue-cesium-draw#8]
您好，我在尝试cesium地图上实现绘制/加载标注，基于您的drawhandler.js实现了功能，但在绘制多个图形时出现了明显的帧率下降和卡顿（没有使用您包装好的组件，也没有将生成的cesium viewer instance放入vue的data）。
这是加载了29个标注图形的结果，移动和缩放基本会卡死，体验非常差。想请问下，可能是什么原因导致的卡顿？单纯的添加entity应该不至于这样，可能是eventhandler或者collection里用map维护的graph instance导致的吗？

![image](https://user-images.githubusercontent.com/32822916/66962798-f1180580-f03f-11e9-9924-938905a9c9a1.png)
![image](https://user-images.githubusercontent.com/32822916/66962904-376d6480-f040-11e9-8b8b-3e48c2dc6dfb.png)

多谢！

**Comment by xtfge** [comment]
可能是监听事件太多造成的，每个graphic或着marker都会有两个鼠标事件的监听，这会消耗大量的资源，最好的应该是所有对象共同使用一个事件监听。

**Comment by skywalkershen** [comment]
> 可能是监听事件太多造成的，每个graphic或着marker都会有两个鼠标事件的监听，这会消耗大量的资源，最好的应该是所有对象共同使用一个事件监听。

但是每个对象handler里面的具体参数不同，这个不太好直接用一个监听吧？而且比如已经import了一些geojson,我再手动画一个的话，岂不是又需要新的handler或是得unbind之前的

**Comment by xtfge** [comment]
你可以把同类对象（mark/polyline/polygon)保存到一个Map中，然后在监听事件中判断当前的对象是哪个，在调用它相应的方法，比如
```js
const plCollection=new Map()
const pl1=new Polyline()
const pl2=new Polyline()
plCollection.set(pl1.id,pl1)
plCollection.set(pl2.id,pl2)
handler.setInputAction(function(e){
const obj=scene.pick(e.position)
if(plCollection.has(obj.id.id){
const pl=plCollection.get(obj.id.id)
//pl相关操作
}
},Cesium.ScreenSpaceEventType.LEFT_CLICK)
```
需要说明的是你需要在创建Entity对象的时候设置id。
